spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: <insert email here>
    password: <insert password here>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
security:
  jwt:
    secret-key: kylerequez
server:
  port: 8080